import Header from '@/layouts/header';
import { HEADER_HEIGHT, PX_ALL } from '@/utils/const';
import { Box } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body className={inter.className}>
        <Providers>
          <Box bgColor="#F2F2F2" minH="100vh">
            <Header />
            <Box mt={HEADER_HEIGHT}>
              <Box px={PX_ALL}>{children}</Box>
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
